//
//  WordsForest
//
//  Created by Nami .T on 2025/09/30.
//
//  SampleDeck.swift

import Foundation

enum SampleDeck {
    static func filtered(by pos: PartOfSpeech) -> [WordCard] {
        if let all = loadCSV(), !all.isEmpty {
            let f = all.filter { $0.pos == pos }
            return f.isEmpty ? builtin(by: pos) : f
        }
        return builtin(by: pos)
    }
    // ここに“いまの配列”をそのまま移植
    private static func builtin(by pos: PartOfSpeech) -> [WordCard] {
        switch pos {
        case .noun:
            return [
                
                
                WordCard(word: "apple",  meaning: "りんご", pos: .noun),
                WordCard(word: "river",  meaning: "川",    pos: .noun),
                WordCard(word: "forest", meaning: "森",    pos: .noun),
                WordCard(word: "music",  meaning: "音楽",  pos: .noun),
                WordCard(word: "mountain", meaning: "山", pos: .noun),
                WordCard(word: "ocean", meaning: "海", pos: .noun),
                WordCard(word: "flower", meaning: "花", pos: .noun),
                WordCard(word: "friend", meaning: "友達", pos: .noun),
                WordCard(word: "sun", meaning: "太陽", pos: .noun),
                WordCard(word: "moon", meaning: "月", pos: .noun),
                WordCard(word: "tree", meaning: "木", pos: .noun),
                WordCard(word: "cloud", meaning: "雲", pos: .noun),
                WordCard(word: "book", meaning: "本", pos: .noun),
                WordCard(word: "school", meaning: "学校", pos: .noun),
                WordCard(word: "bird", meaning: "鳥", pos: .noun),
                WordCard(word: "snow", meaning: "雪", pos: .noun),
                WordCard(word: "star", meaning: "星", pos: .noun),
                WordCard(word: "animal", meaning: "動物", pos: .noun),
                WordCard(word: "city", meaning: "都市", pos: .noun),
                WordCard(word: "flowerpot", meaning: "植木鉢", pos: .noun),
                WordCard(word: "dream", meaning: "夢", pos: .noun),
                WordCard(word: "story", meaning: "物語", pos: .noun),
                WordCard(word: "window", meaning: "窓", pos: .noun),
                WordCard(word: "garden", meaning: "庭", pos: .noun),
                WordCard(word: "kitchen", meaning: "台所", pos: .noun),
                WordCard(word: "pencil", meaning: "鉛筆", pos: .noun),
                WordCard(word: "street", meaning: "通り", pos: .noun),
                WordCard(word: "dog", meaning: "犬", pos: .noun),
                WordCard(word: "food", meaning: "食べ物", pos: .noun),
                WordCard(word: "phone", meaning: "電話", pos: .noun),
                WordCard(word: "bag", meaning: "かばん", pos: .noun),
                WordCard(word: "chair", meaning: "椅子", pos: .noun),
                WordCard(word: "table", meaning: "テーブル", pos: .noun),
                WordCard(word: "cup", meaning: "コップ", pos: .noun),
                WordCard(word: "bed", meaning: "ベッド", pos: .noun),
                WordCard(word: "shirt", meaning: "シャツ", pos: .noun),
                WordCard(word: "shoes", meaning: "靴", pos: .noun),
                WordCard(word: "hat", meaning: "帽子", pos: .noun),
                WordCard(word: "water", meaning: "水", pos: .noun),
                WordCard(word: "juice", meaning: "ジュース", pos: .noun),
                WordCard(word: "butter", meaning: "バター", pos: .noun),
                WordCard(word: "bread", meaning: "パン", pos: .noun),
                WordCard(word: "milk", meaning: "牛乳", pos: .noun),
                WordCard(word: "egg", meaning: "卵", pos: .noun),
                WordCard(word: "car", meaning: "車", pos: .noun),
                WordCard(word: "train", meaning: "電車", pos: .noun),
                WordCard(word: "bus", meaning: "バス", pos: .noun),
                WordCard(word: "key", meaning: "鍵", pos: .noun),
                WordCard(word: "door", meaning: "ドア", pos: .noun),
                WordCard(word: "house", meaning: "家", pos: .noun),
                WordCard(word: "mirror", meaning: "鏡", pos: .noun),
                WordCard(word: "clock", meaning: "時計", pos: .noun),
                WordCard(word: "watch", meaning: "腕時計", pos: .noun),
                WordCard(word: "soap", meaning: "石けん", pos: .noun),
                WordCard(word: "towel", meaning: "タオル", pos: .noun),
                WordCard(word: "toothbrush", meaning: "歯ブラシ", pos: .noun),
                WordCard(word: "windowpane", meaning: "窓ガラス", pos: .noun),
                WordCard(word: "notebook", meaning: "ノート", pos: .noun),
                WordCard(word: "letter", meaning: "手紙", pos: .noun),
                WordCard(word: "photo", meaning: "写真", pos: .noun),
                WordCard(word: "library", meaning: "図書館", pos: .noun),
                WordCard(word: "museum", meaning: "博物館", pos: .noun),
                WordCard(word: "station", meaning: "駅", pos: .noun),
                WordCard(word: "corner", meaning: "角", pos: .noun),
                WordCard(word: "guest", meaning: "招待客", pos: .noun),
                WordCard(word: "schedule", meaning: "予定", pos: .noun),
                WordCard(word: "message", meaning: "伝言", pos: .noun),
                WordCard(word: "question", meaning: "質問", pos: .noun),
                WordCard(word: "mistake", meaning: "まちがい", pos: .noun),
                WordCard(word: "practice", meaning: "練習", pos: .noun),
                WordCard(word: "festival", meaning: "祭り", pos: .noun),
                WordCard(word: "language", meaning: "言語", pos: .noun),
                WordCard(word: "classroom", meaning: "教室", pos: .noun),
                WordCard(word: "homework", meaning: "宿題", pos: .noun),
                WordCard(word: "answer", meaning: "答え", pos: .noun),
                WordCard(word: "example", meaning: "例", pos: .noun),
                WordCard(word: "problem", meaning: "問題", pos: .noun),
                WordCard(word: "meeting", meaning: "会議", pos: .noun),
                WordCard(word: "plan", meaning: "計画", pos: .noun),
                WordCard(word: "list", meaning: "リスト", pos: .noun),
                WordCard(word: "ticket", meaning: "切符", pos: .noun),
                WordCard(word: "wallet", meaning: "財布", pos: .noun),
                WordCard(word: "umbrella", meaning: "傘", pos: .noun),
                WordCard(word: "medicine", meaning: "薬", pos: .noun),
                WordCard(word: "breakfast", meaning: "朝食", pos: .noun),
                WordCard(word: "lunch", meaning: "昼食", pos: .noun),
                WordCard(word: "dinner", meaning: "夕食", pos: .noun),
                WordCard(word: "assignment", meaning: "課題", pos: .noun),
                WordCard(word: "blackboard", meaning: "黒板", pos: .noun),
                WordCard(word: "dictionary", meaning: "辞書", pos: .noun),
                WordCard(word: "grade", meaning: "成績", pos: .noun),
                WordCard(word: "group", meaning: "班", pos: .noun),
                WordCard(word: "hint", meaning: "ヒント", pos: .noun),
                WordCard(word: "idea", meaning: "考え", pos: .noun),
                WordCard(word: "project", meaning: "課題研究", pos: .noun),
                WordCard(word: "report", meaning: "レポート", pos: .noun),
                WordCard(word: "rule", meaning: "規則", pos: .noun),
                WordCard(word: "sentence", meaning: "文", pos: .noun),
                WordCard(word: "test", meaning: "テスト", pos: .noun),
                WordCard(word: "bathroom", meaning: "浴室", pos: .noun),
                WordCard(word: "blanket", meaning: "毛布", pos: .noun),
                WordCard(word: "dish", meaning: "皿", pos: .noun),
                WordCard(word: "drawer", meaning: "引き出し", pos: .noun),
                WordCard(word: "floor", meaning: "床", pos: .noun),
                WordCard(word: "fridge", meaning: "冷蔵庫", pos: .noun),
                WordCard(word: "laundry", meaning: "洗濯物", pos: .noun),
                WordCard(word: "pillow", meaning: "枕", pos: .noun),
                WordCard(word: "shower", meaning: "シャワー", pos: .noun),
                WordCard(word: "bridge", meaning: "橋", pos: .noun),
                WordCard(word: "bus stop", meaning: "バス停", pos: .noun),
                WordCard(word: "crosswalk", meaning: "横断歩道", pos: .noun),
                WordCard(word: "entrance", meaning: "入口", pos: .noun),
                WordCard(word: "exit", meaning: "出口", pos: .noun),
                WordCard(word: "gate", meaning: "門", pos: .noun),
                WordCard(word: "map", meaning: "地図", pos: .noun),
                WordCard(word: "passenger", meaning: "乗客", pos: .noun),
                WordCard(word: "road", meaning: "道路", pos: .noun),
                WordCard(word: "sidewalk", meaning: "歩道", pos: .noun),
                WordCard(word: "sign", meaning: "標識", pos: .noun),
                WordCard(word: "traffic light", meaning: "信号", pos: .noun),
                WordCard(word: "anger", meaning: "怒り", pos: .noun),
                WordCard(word: "choice", meaning: "選択", pos: .noun),
                WordCard(word: "fear", meaning: "恐れ", pos: .noun),
                WordCard(word: "feeling", meaning: "気持ち", pos: .noun),
                WordCard(word: "hope", meaning: "希望", pos: .noun),
                WordCard(word: "joy", meaning: "喜び", pos: .noun),
                WordCard(word: "kindness", meaning: "親切", pos: .noun),
                WordCard(word: "memory", meaning: "記憶", pos: .noun),
                WordCard(word: "promise", meaning: "約束", pos: .noun),
                WordCard(word: "reason", meaning: "理由", pos: .noun),
                WordCard(word: "worry", meaning: "心配", pos: .noun),
                WordCard(word: "bakery", meaning: "パン屋", pos: .noun),
                WordCard(word: "bill", meaning: "勘定書", pos: .noun),
                WordCard(word: "cashier", meaning: "レジ係", pos: .noun),
                WordCard(word: "change", meaning: "おつり", pos: .noun),
                WordCard(word: "customer", meaning: "顧客", pos: .noun),
                WordCard(word: "discount", meaning: "値引き", pos: .noun),
                WordCard(word: "market", meaning: "市場", pos: .noun),
                WordCard(word: "price", meaning: "値段", pos: .noun),
                WordCard(word: "receipt", meaning: "レシート", pos: .noun),
                WordCard(word: "sale", meaning: "特売", pos: .noun),
                WordCard(word: "autumn", meaning: "秋", pos: .noun),
                WordCard(word: "breeze", meaning: "そよ風", pos: .noun),
                WordCard(word: "cloud", meaning: "雲", pos: .noun),
                WordCard(word: "forecast", meaning: "天気予報", pos: .noun),
                WordCard(word: "lightning", meaning: "稲光", pos: .noun),
                WordCard(word: "rainbow", meaning: "虹", pos: .noun),
                WordCard(word: "season", meaning: "季節", pos: .noun),
                WordCard(word: "shade", meaning: "日陰", pos: .noun),
                WordCard(word: "snowfall", meaning: "降雪", pos: .noun),
                WordCard(word: "sunshine", meaning: "日光", pos: .noun),
            ]
        case .verb:
            return [
                
                WordCard(word: "run",   meaning: "走る", pos: .verb),
                WordCard(word: "fly",   meaning: "飛ぶ", pos: .verb),
                WordCard(word: "write", meaning: "書く", pos: .verb),
                WordCard(word: "think", meaning: "考える", pos: .verb),
                WordCard(word: "read", meaning: "読む", pos: .verb),
                WordCard(word: "eat", meaning: "食べる", pos: .verb),
                WordCard(word: "sleep", meaning: "眠る", pos: .verb),
                WordCard(word: "sing", meaning: "歌う", pos: .verb),
                WordCard(word: "listen", meaning: "聞く", pos: .verb),
                WordCard(word: "watch", meaning: "見る", pos: .verb),
                WordCard(word: "draw", meaning: "描く", pos: .verb),
                WordCard(word: "build", meaning: "作る", pos: .verb),
                WordCard(word: "swim", meaning: "泳ぐ", pos: .verb),
                WordCard(word: "walk", meaning: "歩く", pos: .verb),
                WordCard(word: "smile", meaning: "ほほえむ", pos: .verb),
                WordCard(word: "laugh", meaning: "笑う", pos: .verb),
                WordCard(word: "open", meaning: "開ける", pos: .verb),
                WordCard(word: "close", meaning: "閉める", pos: .verb),
                WordCard(word: "help", meaning: "助ける", pos: .verb),
                WordCard(word: "cook", meaning: "料理する", pos: .verb),
                WordCard(word: "climb", meaning: "登る", pos: .verb),
                WordCard(word: "wait", meaning: "待つ", pos: .verb),
                WordCard(word: "hope", meaning: "望む", pos: .verb),
                WordCard(word: "learn", meaning: "学ぶ", pos: .verb),
                WordCard(word: "sell", meaning: "売る", pos: .verb),
                 WordCard(word: "use", meaning: "使う", pos: .verb),
                 WordCard(word: "carry", meaning: "運ぶ", pos: .verb),
                 WordCard(word: "drive", meaning: "運転する", pos: .verb),
                 WordCard(word: "ride", meaning: "乗る", pos: .verb),
                 WordCard(word: "wash", meaning: "洗う", pos: .verb),
                 WordCard(word: "clean", meaning: "掃除する", pos: .verb),
                 WordCard(word: "talk", meaning: "話す", pos: .verb),
                 WordCard(word: "call", meaning: "電話する", pos: .verb),
                 WordCard(word: "meet", meaning: "会う", pos: .verb),
                 WordCard(word: "study", meaning: "勉強する", pos: .verb),
                 WordCard(word: "play", meaning: "遊ぶ", pos: .verb),
                 WordCard(word: "paint", meaning: "塗る", pos: .verb),
                 WordCard(word: "dance", meaning: "踊る", pos: .verb),
                 WordCard(word: "drink", meaning: "飲む", pos: .verb),
                 WordCard(word: "look", meaning: "見る", pos: .verb),
                 WordCard(word: "see", meaning: "見える", pos: .verb),
                 WordCard(word: "throw", meaning: "投げる", pos: .verb),
                 WordCard(word: "catch", meaning: "捕まえる", pos: .verb),
                 WordCard(word: "pick", meaning: "拾う", pos: .verb),
                 WordCard(word: "put", meaning: "置く", pos: .verb),
                 WordCard(word: "bring", meaning: "持ってくる", pos: .verb),
                 WordCard(word: "take", meaning: "持っていく", pos: .verb),
                 WordCard(word: "show", meaning: "見せる", pos: .verb),
                 WordCard(word: "teach", meaning: "教える", pos: .verb),
                 WordCard(word: "love", meaning: "愛する", pos: .verb),
                 WordCard(word: "like", meaning: "好き", pos: .verb),
                 WordCard(word: "hate", meaning: "嫌う", pos: .verb),
                 WordCard(word: "jump", meaning: "跳ぶ", pos: .verb),
                 WordCard(word: "sit", meaning: "座る", pos: .verb),
                 WordCard(word: "stand", meaning: "立つ", pos: .verb),
                 WordCard(word: "hug", meaning: "抱きしめる", pos: .verb),
                 WordCard(word: "want", meaning: "欲しい", pos: .verb),
                 WordCard(word: "bake", meaning: "焼く", pos: .verb),
                WordCard(word: "play", meaning: "遊ぶ", pos: .verb),
                WordCard(word: "arrive", meaning: "到着する", pos: .verb),
                WordCard(word: "borrow", meaning: "借りる", pos: .verb),
                WordCard(word: "choose", meaning: "選ぶ", pos: .verb),
                WordCard(word: "close", meaning: "閉める", pos: .verb),
                WordCard(word: "continue", meaning: "続ける", pos: .verb),
                WordCard(word: "happen", meaning: "起こる", pos: .verb),
                WordCard(word: "invite", meaning: "招待する", pos: .verb),
                WordCard(word: "prepare", meaning: "準備する", pos: .verb),
                WordCard(word: "return", meaning: "戻る", pos: .verb),
                WordCard(word: "share", meaning: "分け合う", pos: .verb),
                WordCard(word: "stay", meaning: "滞在する", pos: .verb),
                WordCard(word: "travel", meaning: "旅行する", pos: .verb),
                WordCard(word: "answer", meaning: "答える", pos: .verb),
                WordCard(word: "ask", meaning: "たずねる", pos: .verb),
                WordCard(word: "check", meaning: "確認する", pos: .verb),
                WordCard(word: "finish", meaning: "終える", pos: .verb),
                WordCard(word: "forget", meaning: "忘れる", pos: .verb),
                WordCard(word: "leave", meaning: "出発する", pos: .verb),
                WordCard(word: "need", meaning: "必要とする", pos: .verb),
                WordCard(word: "remember", meaning: "覚えている", pos: .verb),
                WordCard(word: "start", meaning: "始める", pos: .verb),
                WordCard(word: "compare", meaning: "比べる", pos: .verb),
                WordCard(word: "copy", meaning: "写す", pos: .verb),
                WordCard(word: "discuss", meaning: "話し合う", pos: .verb),
                WordCard(word: "explain", meaning: "説明する", pos: .verb),
                WordCard(word: "hand", meaning: "手渡す", pos: .verb),
                WordCard(word: "improve", meaning: "改善する", pos: .verb),
                WordCard(word: "include", meaning: "含む", pos: .verb),
                WordCard(word: "mark", meaning: "印をつける", pos: .verb),
                WordCard(word: "review", meaning: "復習する", pos: .verb),
                WordCard(word: "solve", meaning: "解く", pos: .verb),
                WordCard(word: "submit", meaning: "提出する", pos: .verb),
                WordCard(word: "underline", meaning: "下線を引く", pos: .verb),
                WordCard(word: "boil", meaning: "ゆでる", pos: .verb),
                WordCard(word: "brush", meaning: "みがく", pos: .verb),
                WordCard(word: "change", meaning: "着替える", pos: .verb),
                WordCard(word: "dry", meaning: "乾かす", pos: .verb),
                WordCard(word: "fold", meaning: "たたむ", pos: .verb),
                WordCard(word: "heat", meaning: "温める", pos: .verb),
                WordCard(word: "pack", meaning: "荷造りする", pos: .verb),
                WordCard(word: "rest", meaning: "休む", pos: .verb),
                WordCard(word: "set", meaning: "置く", pos: .verb),
                WordCard(word: "tidy", meaning: "片づける", pos: .verb),
                WordCard(word: "wake", meaning: "目を覚ます", pos: .verb),
                WordCard(word: "cross", meaning: "横切る", pos: .verb),
                WordCard(word: "follow", meaning: "ついて行く", pos: .verb),
                WordCard(word: "hurry", meaning: "急ぐ", pos: .verb),
                WordCard(word: "miss", meaning: "乗りそこなう", pos: .verb),
                WordCard(word: "pass", meaning: "通り過ぎる", pos: .verb),
                WordCard(word: "reach", meaning: "着く", pos: .verb),
                WordCard(word: "stop", meaning: "止まる", pos: .verb),
                WordCard(word: "turn", meaning: "曲がる", pos: .verb),
                WordCard(word: "visit", meaning: "訪れる", pos: .verb),
                WordCard(word: "agree", meaning: "賛成する", pos: .verb),
                WordCard(word: "believe", meaning: "信じる", pos: .verb),
                WordCard(word: "calm", meaning: "落ち着かせる", pos: .verb),
                WordCard(word: "care", meaning: "気にかける", pos: .verb),
                WordCard(word: "cheer", meaning: "元気づける", pos: .verb),
                WordCard(word: "doubt", meaning: "疑う", pos: .verb),
                WordCard(word: "notice", meaning: "気づく", pos: .verb),
                WordCard(word: "regret", meaning: "後悔する", pos: .verb),
                WordCard(word: "relax", meaning: "くつろぐ", pos: .verb),
                WordCard(word: "buy", meaning: "買う", pos: .verb),
                WordCard(word: "cost", meaning: "費用がかかる", pos: .verb),
                WordCard(word: "exchange", meaning: "交換する", pos: .verb),
                WordCard(word: "order", meaning: "注文する", pos: .verb),
                WordCard(word: "spend", meaning: "使う（お金を）", pos: .verb),
                WordCard(word: "try", meaning: "試す", pos: .verb),
                WordCard(word: "freeze", meaning: "凍る", pos: .verb),
                WordCard(word: "melt", meaning: "溶ける", pos: .verb),
                WordCard(word: "rain", meaning: "雨が降る", pos: .verb),
                WordCard(word: "shine", meaning: "照る", pos: .verb),
                WordCard(word: "snow", meaning: "雪が降る", pos: .verb),
                WordCard(word: "warm", meaning: "暖める", pos: .verb),
            ]
        case .adj:
            return [
                WordCard(word: "gentle", meaning: "優しい",   pos: .adj),
                WordCard(word: "quiet",  meaning: "静かな",   pos: .adj),
                WordCard(word: "bright", meaning: "明るい",   pos: .adj),
                WordCard(word: "mossy",  meaning: "苔むした", pos: .adj),
                WordCard(word: "happy", meaning: "幸せな", pos: .adj),
                WordCard(word: "sad", meaning: "悲しい", pos: .adj),
                WordCard(word: "cold", meaning: "寒い", pos: .adj),
                WordCard(word: "hot", meaning: "暑い", pos: .adj),
                WordCard(word: "small", meaning: "小さい", pos: .adj),
                WordCard(word: "large", meaning: "大きい", pos: .adj),
                WordCard(word: "fast", meaning: "速い", pos: .adj),
                WordCard(word: "slow", meaning: "遅い", pos: .adj),
                WordCard(word: "old", meaning: "古い", pos: .adj),
                WordCard(word: "new", meaning: "新しい", pos: .adj),
                WordCard(word: "kind", meaning: "親切な", pos: .adj),
                WordCard(word: "funny", meaning: "おかしな", pos: .adj),
                WordCard(word: "scary", meaning: "怖い", pos: .adj),
                WordCard(word: "blue", meaning: "青い", pos: .adj),
                WordCard(word: "green", meaning: "緑の", pos: .adj),
                WordCard(word: "clean", meaning: "きれいな", pos: .adj),
                WordCard(word: "dirty", meaning: "汚れた", pos: .adj),
                WordCard(word: "sharp", meaning: "鋭い", pos: .adj),
                WordCard(word: "soft", meaning: "柔らかい", pos: .adj),
                WordCard(word: "strong", meaning: "強い", pos: .adj),
                WordCard(word: "tall", meaning: "背の高い", pos: .adj),
                WordCard(word: "short", meaning: "背の低い", pos: .adj),
                WordCard(word: "warm", meaning: "暖かい", pos: .adj),
                WordCard(word: "cool", meaning: "涼しい", pos: .adj),
                WordCard(word: "dark", meaning: "暗い", pos: .adj),
                WordCard(word: "light", meaning: "軽い", pos: .adj),
                WordCard(word: "sweet", meaning: "甘い", pos: .adj),
                WordCard(word: "sour", meaning: "酸っぱい", pos: .adj),
                WordCard(word: "bitter", meaning: "苦い", pos: .adj),
                WordCard(word: "salty", meaning: "しょっぱい", pos: .adj),
                WordCard(word: "tired", meaning: "疲れた", pos: .adj),
                WordCard(word: "sleepy", meaning: "眠い", pos: .adj),
                WordCard(word: "hungry", meaning: "お腹がすいた", pos: .adj),
                WordCard(word: "thirsty", meaning: "喉が渇いた", pos: .adj),
                WordCard(word: "busy", meaning: "忙しい", pos: .adj),
                WordCard(word: "free", meaning: "自由な", pos: .adj),
                WordCard(word: "fun", meaning: "楽しい", pos: .adj),
                WordCard(word: "boring", meaning: "退屈な", pos: .adj),
                WordCard(word: "noisy", meaning: "うるさい", pos: .adj),
                WordCard(word: "beautiful", meaning: "美しい", pos: .adj),
                WordCard(word: "ugly", meaning: "醜い", pos: .adj),
                WordCard(word: "thin", meaning: "細い", pos: .adj),
                WordCard(word: "fat", meaning: "太った", pos: .adj),
                WordCard(word: "young", meaning: "若い", pos: .adj),
                WordCard(word: "angry", meaning: "怒っている", pos: .adj),
                WordCard(word: "easy", meaning: "簡単な", pos: .adj),
                WordCard(word: "difficult", meaning: "難しい", pos: .adj),
                WordCard(word: "rich", meaning: "裕福な", pos: .adj),
                WordCard(word: "poor", meaning: "貧しい", pos: .adj),
                WordCard(word: "important", meaning: "大事な", pos: .adj),
                WordCard(word: "interesting", meaning: "面白い", pos: .adj),
                WordCard(word: "warm", meaning: "あたたかい", pos: .adj),
                WordCard(word: "dark", meaning: "暗い", pos: .adj),
                WordCard(word: "friendly", meaning: "親しみやすい", pos: .adj),
                WordCard(word: "busy", meaning: "忙しい", pos: .adj),
                WordCard(word: "safe", meaning: "安全な", pos: .adj),
                WordCard(word: "careful", meaning: "注意深い", pos: .adj),
                WordCard(word: "different", meaning: "異なる", pos: .adj),
                WordCard(word: "famous", meaning: "有名な", pos: .adj),
                WordCard(word: "helpful", meaning: "助けになる", pos: .adj),
                WordCard(word: "hungry", meaning: "お腹がすいた", pos: .adj),
                WordCard(word: "nervous", meaning: "緊張した", pos: .adj),
                WordCard(word: "calm", meaning: "冷静な", pos: .adj),
                WordCard(word: "ready", meaning: "準備ができた", pos: .adj),
                WordCard(word: "special", meaning: "特別な", pos: .adj),
                WordCard(word: "useful", meaning: "役に立つ", pos: .adj),
                WordCard(word: "warm", meaning: "暖かい", pos: .adj),
                WordCard(word: "wide", meaning: "幅の広い", pos: .adj),
                WordCard(word: "dirty", meaning: "汚れた", pos: .adj),
                WordCard(word: "early", meaning: "早い", pos: .adj),
                WordCard(word: "important", meaning: "重要な", pos: .adj),
                WordCard(word: "late", meaning: "遅い", pos: .adj),
                WordCard(word: "near", meaning: "近い", pos: .adj),
                WordCard(word: "right", meaning: "正しい", pos: .adj),
                WordCard(word: "same", meaning: "同じ", pos: .adj),
                WordCard(word: "sick", meaning: "具合の悪い", pos: .adj),
                WordCard(word: "strong", meaning: "強い", pos: .adj),
                WordCard(word: "tired", meaning: "疲れた", pos: .adj),
                WordCard(word: "useful", meaning: "役に立つ", pos: .adj),
                WordCard(word: "wrong", meaning: "まちがった", pos: .adj),
                WordCard(word: "absent", meaning: "欠席の", pos: .adj),
                WordCard(word: "correct", meaning: "正しい", pos: .adj),
                WordCard(word: "excellent", meaning: "すばらしい", pos: .adj),
                WordCard(word: "final", meaning: "最後の", pos: .adj),
                WordCard(word: "main", meaning: "主な", pos: .adj),
                WordCard(word: "necessary", meaning: "必要な", pos: .adj),
                WordCard(word: "present", meaning: "出席している", pos: .adj),
                WordCard(word: "simple", meaning: "簡単な", pos: .adj),
                WordCard(word: "true", meaning: "本当の", pos: .adj),
                WordCard(word: "useful", meaning: "役に立つ", pos: .adj),
                WordCard(word: "written", meaning: "書かれた", pos: .adj),
                WordCard(word: "awake", meaning: "目が覚めている", pos: .adj),
                WordCard(word: "comfortable", meaning: "心地よい", pos: .adj),
                WordCard(word: "empty", meaning: "空っぽの", pos: .adj),
                WordCard(word: "full", meaning: "いっぱいの", pos: .adj),
                WordCard(word: "heavy", meaning: "重い", pos: .adj),
                WordCard(word: "light", meaning: "軽い", pos: .adj),
                WordCard(word: "noisy", meaning: "うるさい", pos: .adj),
                WordCard(word: "soft", meaning: "やわらかい", pos: .adj),
                WordCard(word: "wet", meaning: "ぬれた", pos: .adj),
                WordCard(word: "crowded", meaning: "混んだ", pos: .adj),
                WordCard(word: "far", meaning: "遠い", pos: .adj),
                WordCard(word: "local", meaning: "地元の", pos: .adj),
                WordCard(word: "lost", meaning: "道に迷った", pos: .adj),
                WordCard(word: "straight", meaning: "まっすぐな", pos: .adj),
                WordCard(word: "traffic", meaning: "交通の", pos: .adj),
                WordCard(word: "vacant", meaning: "空いている", pos: .adj),
                WordCard(word: "wide", meaning: "広い", pos: .adj),
                WordCard(word: "afraid", meaning: "こわい", pos: .adj),
                WordCard(word: "brave", meaning: "勇敢な", pos: .adj),
                WordCard(word: "calm", meaning: "落ち着いた", pos: .adj),
                WordCard(word: "glad", meaning: "うれしい", pos: .adj),
                WordCard(word: "lonely", meaning: "さびしい", pos: .adj),
                WordCard(word: "proud", meaning: "誇らしい", pos: .adj),
                WordCard(word: "relaxed", meaning: "くつろいだ", pos: .adj),
                WordCard(word: "sad", meaning: "悲しい", pos: .adj),
                WordCard(word: "serious", meaning: "深刻な", pos: .adj),
                WordCard(word: "surprised", meaning: "驚いた", pos: .adj),
                WordCard(word: "upset", meaning: "動揺した", pos: .adj),
                WordCard(word: "cheap", meaning: "安い", pos: .adj),
                WordCard(word: "expensive", meaning: "高価な", pos: .adj),
                WordCard(word: "fresh", meaning: "新鮮な", pos: .adj),
                WordCard(word: "open", meaning: "営業している", pos: .adj),
                WordCard(word: "popular", meaning: "人気のある", pos: .adj),
                WordCard(word: "sold out", meaning: "売り切れの", pos: .adj),
                WordCard(word: "cloudy", meaning: "くもった", pos: .adj),
                WordCard(word: "dry", meaning: "乾燥した", pos: .adj),
                WordCard(word: "foggy", meaning: "霧の深い", pos: .adj),
                WordCard(word: "rainy", meaning: "雨の", pos: .adj),
                WordCard(word: "windy", meaning: "風の強い", pos: .adj),
            ]
        case .adv:
            return [
    
                WordCard(word: "slowly",   meaning: "ゆっくり", pos: .adv),
                WordCard(word: "quickly",  meaning: "素早く",   pos: .adv),
                WordCard(word: "carefully",meaning: "注意深く", pos: .adv),
                WordCard(word: "often",    meaning: "しばしば", pos: .adv),
                WordCard(word: "happily", meaning: "幸せそうに", pos: .adv),
                WordCard(word: "sadly", meaning: "悲しそうに", pos: .adv),
                WordCard(word: "neatly", meaning: "きちんと", pos: .adv),
                WordCard(word: "loudly", meaning: "大声で", pos: .adv),
                WordCard(word: "silently", meaning: "静かに", pos: .adv),
                WordCard(word: "eagerly", meaning: "熱心に", pos: .adv),
                WordCard(word: "gently", meaning: "優しく", pos: .adv),
                WordCard(word: "bravely", meaning: "勇敢に", pos: .adv),
                WordCard(word: "brightly", meaning: "明るく", pos: .adv),
                WordCard(word: "calmly", meaning: "落ち着いて", pos: .adv),
                WordCard(word: "early", meaning: "早く", pos: .adv),
                WordCard(word: "late", meaning: "遅く", pos: .adv),
                WordCard(word: "rarely", meaning: "めったに〜ない", pos: .adv),
                WordCard(word: "daily", meaning: "毎日", pos: .adv),
                WordCard(word: "never", meaning: "決して〜ない", pos: .adv),
                WordCard(word: "apart", meaning: "離れて", pos: .adv),
                WordCard(word: "somewhere", meaning: "どこかで", pos: .adv),
                WordCard(word: "inside", meaning: "中で", pos: .adv),
                WordCard(word: "outside", meaning: "外で", pos: .adv),
                WordCard(word: "quickly",   meaning: "素早く",         pos: .adv),
                WordCard(word: "carefully", meaning: "注意深く",       pos: .adv),
                
                WordCard(word: "apart",     meaning: "離れて",         pos: .adv),
                WordCard(word: "easily",    meaning: "簡単に",         pos: .adv),
                WordCard(word: "really",    meaning: "本当に",         pos: .adv),
                WordCard(word: "maybe",     meaning: "たぶん",         pos: .adv),
                WordCard(word: "again",     meaning: "もう一度",       pos: .adv),
                WordCard(word: "safely",    meaning: "安全に",         pos: .adv),
                WordCard(word: "kindly",    meaning: "親切に",         pos: .adv),
                WordCard(word: "gracefully",meaning: "優雅に",         pos: .adv),
                WordCard(word: "angrily",   meaning: "怒って",         pos: .adv),
                WordCard(word: "fortunately",meaning: "幸運にも",     pos: .adv),
                WordCard(word: "unfortunately", meaning: "不運にも",   pos: .adv),
                WordCard(word: "exactly",   meaning: "正確に",         pos: .adv),
                WordCard(word: "anywhere",  meaning: "どこでも",       pos: .adv),
                WordCard(word: "already", meaning: "すでに", pos: .adv),
                WordCard(word: "certainly", meaning: "確かに", pos: .adv),
                WordCard(word: "everywhere", meaning: "いたるところで", pos: .adv),
                WordCard(word: "finally", meaning: "ついに", pos: .adv),
                WordCard(word: "forward", meaning: "前へ", pos: .adv),
                WordCard(word: "perhaps", meaning: "もしかすると", pos: .adv),
                WordCard(word: "recently", meaning: "最近", pos: .adv),
                WordCard(word: "sometimes", meaning: "ときどき", pos: .adv),
                WordCard(word: "suddenly", meaning: "突然", pos: .adv),
                WordCard(word: "upstairs", meaning: "上の階で", pos: .adv),
                WordCard(word: "always", meaning: "いつも", pos: .adv),
                WordCard(word: "carefully", meaning: "注意深く", pos: .adv),
                WordCard(word: "early", meaning: "早く", pos: .adv),
                WordCard(word: "fast", meaning: "速く", pos: .adv),
                WordCard(word: "here", meaning: "ここで", pos: .adv),
                WordCard(word: "late", meaning: "遅く", pos: .adv),
                WordCard(word: "later", meaning: "あとで", pos: .adv),
                WordCard(word: "now", meaning: "今", pos: .adv),
                WordCard(word: "outside", meaning: "外で", pos: .adv),
                WordCard(word: "soon", meaning: "すぐに", pos: .adv),
                WordCard(word: "there", meaning: "そこで", pos: .adv),
                WordCard(word: "today", meaning: "今日", pos: .adv),
                WordCard(word: "tomorrow", meaning: "明日", pos: .adv),
                WordCard(word: "together", meaning: "いっしょに", pos: .adv),
                WordCard(word: "usually", meaning: "たいてい", pos: .adv),
                WordCard(word: "aloud", meaning: "声に出して", pos: .adv),
                WordCard(word: "clearly", meaning: "はっきりと", pos: .adv),
                WordCard(word: "correctly", meaning: "正しく", pos: .adv),
                WordCard(word: "directly", meaning: "直接", pos: .adv),
                WordCard(word: "especially", meaning: "特に", pos: .adv),
                WordCard(word: "individually", meaning: "各自で", pos: .adv),
                WordCard(word: "quietly", meaning: "静かに", pos: .adv),
                WordCard(word: "separately", meaning: "別々に", pos: .adv),
                WordCard(word: "twice", meaning: "2回", pos: .adv),
                WordCard(word: "wrongly", meaning: "まちがって", pos: .adv),
                WordCard(word: "back", meaning: "後ろへ", pos: .adv),
                WordCard(word: "downstairs", meaning: "下の階で", pos: .adv),
                WordCard(word: "hard", meaning: "一生けん命", pos: .adv),
                WordCard(word: "just", meaning: "ちょうど", pos: .adv),
                WordCard(word: "nearly", meaning: "ほとんど", pos: .adv),
                WordCard(word: "still", meaning: "まだ", pos: .adv),
                WordCard(word: "then", meaning: "それから", pos: .adv),
                WordCard(word: "upstairs", meaning: "上の階で", pos: .adv),
                WordCard(word: "yet", meaning: "まだ", pos: .adv),
                WordCard(word: "abroad", meaning: "海外へ", pos: .adv),
                WordCard(word: "downtown", meaning: "街中へ", pos: .adv),
                WordCard(word: "east", meaning: "東へ", pos: .adv),
                WordCard(word: "home", meaning: "家へ", pos: .adv),
                WordCard(word: "left", meaning: "左へ", pos: .adv),
                WordCard(word: "nearby", meaning: "近くに", pos: .adv),
                WordCard(word: "north", meaning: "北へ", pos: .adv),
                WordCard(word: "right", meaning: "右へ", pos: .adv),
                WordCard(word: "south", meaning: "南へ", pos: .adv),
                WordCard(word: "west", meaning: "西へ", pos: .adv),
                WordCard(word: "anyway", meaning: "何でも", pos: .adv),
                WordCard(word: "brightly", meaning: "明るく", pos: .adv),
                WordCard(word: "calmly", meaning: "落ち着いて", pos: .adv),
                WordCard(word: "deeply", meaning: "深く", pos: .adv),
                WordCard(word: "happily", meaning: "幸せそうに", pos: .adv),
                WordCard(word: "honestly", meaning: "正直に", pos: .adv),
                WordCard(word: "seriously", meaning: "まじめに", pos: .adv),
                WordCard(word: "cheaply", meaning: "安く", pos: .adv),
                WordCard(word: "daily", meaning: "毎日", pos: .adv),
                WordCard(word: "instead", meaning: "代わりに", pos: .adv),
                WordCard(word: "online", meaning: "オンラインで", pos: .adv),
                WordCard(word: "very", meaning: "とても", pos: .adv),
                WordCard(word: "overnight", meaning: "一晩で", pos: .adv),
            ]
        case .others:
            return [
                WordCard(word: "the",  meaning: "定冠詞　その〜、例の", pos: .others),
                WordCard(word: "a",    meaning: "不定冠詞　ある〜、ひとつの", pos: .others),
                WordCard(word: "in",   meaning: "前置詞　〜の中で",   pos: .others),
                WordCard(word: "on",   meaning: "前置詞　〜の上に",   pos: .others),
                WordCard(word: "to",   meaning: "前置詞/不定詞　到達点を示す/〜すること",  pos: .others),
                WordCard(word: "and",  meaning: "接続詞　〜と、そして",   pos: .others),
                WordCard(word: "but",  meaning: "接続詞　しかし",   pos: .others),
                WordCard(word: "can",  meaning: "助動詞　〜できる",   pos: .others),
                WordCard(word: "at",   meaning: "前置詞　〜で",   pos: .others),
                WordCard(word: "is", meaning: "be動詞　〜である", pos: .others),
                WordCard(word: "are", meaning: "be動詞　〜である", pos: .others),
                WordCard(word: "was", meaning: "be動詞　amとisの過去形", pos: .others),
                WordCard(word: "were", meaning: "be動詞　areの過去形", pos: .others),
                WordCard(word: "do", meaning: "助動詞/動詞　する", pos: .others),
                WordCard(word: "does", meaning: "助動詞/動詞　〜する(3単現)", pos: .others),
                WordCard(word: "did", meaning: "助動詞/動詞　〜した", pos: .others),
                WordCard(word: "will", meaning: "助動詞　〜するだろう", pos: .others),
                WordCard(word: "if", meaning: "接続詞　もし〜なら", pos: .others),
                WordCard(word: "because", meaning: "接続詞　なぜなら/〜なので", pos: .others),
                WordCard(word: "with", meaning: "前置詞　〜と一緒に", pos: .others),
                WordCard(word: "without", meaning: "前置詞　〜なしで", pos: .others),
                WordCard(word: "under", meaning: "前置詞　〜の下に", pos: .others),
                WordCard(word: "as", meaning: "前置詞/接続詞/副詞 〜として/〜する時/同じくらい", pos: .others),
                WordCard(word: "oh", meaning: "間投詞　おおっ", pos: .others),
                WordCard(word: "hey", meaning: "間投詞　ねえ", pos: .others),
                WordCard(word: "behind", meaning: "前置詞 〜の後ろに", pos: .others),
                WordCard(word: "between", meaning: "前置詞 〜の間に", pos: .others),
                WordCard(word: "through", meaning: "前置詞 〜を通って", pos: .others),
                WordCard(word: "during", meaning: "前置詞 〜の間に", pos: .others),
                WordCard(word: "before", meaning: "前置詞/接続詞 〜の前に", pos: .others),
                WordCard(word: "after", meaning: "前置詞/接続詞 〜の後で", pos: .others),
                WordCard(word: "until", meaning: "前置詞/接続詞 〜まで", pos: .others),
                WordCard(word: "although", meaning: "接続詞 〜だけれども", pos: .others),
                WordCard(word: "when", meaning: "接続詞 〜するとき", pos: .others),
                WordCard(word: "something", meaning: "代名詞 何か", pos: .others),
                WordCard(word: "nothing", meaning: "代名詞 何も〜ないもの", pos: .others),
                WordCard(word: "around", meaning: "前置詞/副詞 〜のまわりに", pos: .others),
                WordCard(word: "because", meaning: "接続詞 なぜなら/〜なので", pos: .others),
                WordCard(word: "someone", meaning: "代名詞 だれか", pos: .others),
                WordCard(word: "everyone", meaning: "代名詞 みんな", pos: .others),
                WordCard(word: "everything", meaning: "代名詞 すべて", pos: .others),
                WordCard(word: "another", meaning: "形容詞/代名詞 もう一つの", pos: .others),
                WordCard(word: "across", meaning: "前置詞/副詞 〜を横切って", pos: .others),
                WordCard(word: "against", meaning: "前置詞 〜に反して", pos: .others),
                WordCard(word: "among", meaning: "前置詞 〜の間で", pos: .others),
                WordCard(word: "both", meaning: "代名詞/形容詞/副詞 両方", pos: .others),
                WordCard(word: "either", meaning: "代名詞/形容詞/副詞 どちらか", pos: .others),
                WordCard(word: "enough", meaning: "形容詞/代名詞/副詞 十分な/十分に", pos: .others),
                WordCard(word: "every", meaning: "形容詞 すべての", pos: .others),
                WordCard(word: "few", meaning: "形容詞/代名詞 ほとんどない/少数", pos: .others),
                WordCard(word: "many", meaning: "形容詞/代名詞 たくさんの", pos: .others),
                WordCard(word: "most", meaning: "形容詞/代名詞/副詞 ほとんどの/最も", pos: .others),
                WordCard(word: "several", meaning: "形容詞/代名詞 いくつかの", pos: .others),
                WordCard(word: "whether", meaning: "接続詞 〜かどうか", pos: .others),
                WordCard(word: "along", meaning: "前置詞/副詞 〜に沿って", pos: .others),
                WordCard(word: "beside", meaning: "前置詞 〜のそばに", pos: .others),
                WordCard(word: "down", meaning: "前置詞/副詞 下へ", pos: .others),
                WordCard(word: "off", meaning: "前置詞/副詞 離れて/消えて", pos: .others),
                WordCard(word: "over", meaning: "前置詞/副詞 〜の上に/上へ", pos: .others),
                WordCard(word: "past", meaning: "前置詞 〜を過ぎて", pos: .others),
                WordCard(word: "since", meaning: "前置詞/接続詞 〜以来/〜なので", pos: .others),
                WordCard(word: "than", meaning: "接続詞/前置詞 〜より", pos: .others),
                WordCard(word: "yourself", meaning: "代名詞 あなた自身", pos: .others),
                WordCard(word: "each", meaning: "形容詞/代名詞 それぞれの", pos: .others),
                WordCard(word: "beyond", meaning: "前置詞 〜の向こうに", pos: .others),
                WordCard(word: "near", meaning: "前置詞 〜の近くに", pos: .others),
                WordCard(word: "onto", meaning: "前置詞 〜の上へ", pos: .others),
                WordCard(word: "toward", meaning: "前置詞 〜の方へ", pos: .others),
                WordCard(word: "via", meaning: "前置詞 〜経由で", pos: .others),
                WordCard(word: "within", meaning: "前置詞 〜の中に", pos: .others),
                WordCard(word: "anyone", meaning: "代名詞 だれでも/だれか", pos: .others),
                WordCard(word: "myself", meaning: "代名詞 私自身", pos: .others),
                WordCard(word: "while", meaning: "接続詞 〜する間", pos: .others),
                WordCard(word: "some", meaning: "形容詞/代名詞 いくつかの", pos: .others),
                WordCard(word: "below", meaning: "前置詞/副詞 〜より下に", pos: .others),
                WordCard(word: "throughout", meaning: "前置詞 〜の間じゅう", pos: .others),
            ]

        }
    }

    // ===== CSV読込 =====
    private static func loadCSV() -> [WordCard]? {
        guard let url = Bundle.main.url(forResource: "SampleDeck", withExtension: "csv"),
              let text = try? String(contentsOf: url, encoding: .utf8)
        else { return nil }

        var rows = text.split(whereSeparator: \.isNewline).map(String.init)
        if let first = rows.first, first.lowercased().contains("word,") {
            rows.removeFirst() // ヘッダ行を除去
        }

        var result: [WordCard] = []
        for line in rows {
            let cols = parseCSVLine(line)
            guard cols.count >= 3,
                  let p = PartOfSpeech.parse(cols[2]) else { continue }
            let w = cols[0].trimmingCharacters(in: .whitespaces)
            let m = cols[1].trimmingCharacters(in: .whitespaces)
            result.append(.init(word: w, meaning: m, pos: p))
        }
        return result
    }

    // ダブルクオート対応の簡易CSVパーサ
    private static func parseCSVLine(_ s: String) -> [String] {
        var res:[String] = []
        var field = ""
        var inQuotes = false
        var i = s.startIndex
        while i < s.endIndex {
            let ch = s[i]
            if ch == "\"" {
                let next = s.index(after: i)
                if inQuotes && next < s.endIndex && s[next] == "\"" {
                    field.append("\""); i = s.index(after: next); continue // 連続""はエスケープ
                }
                inQuotes.toggle()
            } else if ch == "," && !inQuotes {
                res.append(field); field = ""
            } else {
                field.append(ch)
            }
            i = s.index(after: i)
        }
        res.append(field)
        return res
    }
}

extension PartOfSpeech {
    static func parse(_ s: String) -> PartOfSpeech? {
        switch s.lowercased() {
        case "noun","名詞","n": return .noun
        case "verb","動詞","v": return .verb
        case "adjective","形容詞","adj","a": return .adj
        case "adverb","副詞","adv","r": return .adv
        case "others","other","misc","その他","他":  return .others   // ← 追加
        default: return nil
        }
    }
}
